services:
  - type: web
    name: b-transfer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT b_transfer_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
    healthCheckPath: /health 